In [1]:
import numpy as np

##Write a Python program using NumPy to create a 5x5 matrix filled with random integers between 1 and 100. Calculate the mean and standard deviation of the matrix and print them.

In [4]:
#Generating the matrix of random integers between 1-100 in a 5*5 numpy array
matrix = np.random.randint(0,101,(5,5))
matrix

array([[68, 56, 81, 94, 35],
       [99, 74, 38, 48, 31],
       [86, 99, 54, 89, 95],
       [14,  1, 11, 86, 78],
       [92, 52, 77, 43,  2]])

In [6]:
# Mean of the (5*5) numpy array

mean  = np.mean(matrix)
mean

np.float64(60.12)

In [5]:
#Standard deviation of the (5*5) numpy array
std_dev = np.std(matrix)
std_dev

np.float64(30.86398548470369)

##Using NumPy, create a 5x5 identity matrix and add a scalar value of 5 to it. Multiply the resulting matrix with a 5x1 column vector filled with random integers between 1 and 10. Print the resulting vector.



In [47]:
iden_matrix = np.eye(5,5)
iden_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
iden_matrix = iden_matrix + 5
iden_matrix

array([[6., 5., 5., 5., 5.],
       [5., 6., 5., 5., 5.],
       [5., 5., 6., 5., 5.],
       [5., 5., 5., 6., 5.],
       [5., 5., 5., 5., 6.]])

In [49]:
columnvector=np.random.randint(1,11,(5,1))
print(columnvector)
result_matrix = iden_matrix @ columnvector

[[ 2]
 [10]
 [ 9]
 [ 8]
 [ 5]]


In [50]:
result_matrix

array([[172.],
       [180.],
       [179.],
       [178.],
       [175.]])

##Write a Python program using NumPy to create two 3x3 matrices filled with random integers between 1 and 100. Compute their element-wise multiplication, and print the resulting matrix.

In [54]:
matrix_x = np.random.randint(1,101,(3,3))
print(matrix_x)
print()
matrix_y = np.random.randint(1,101,(3,3))
print(matrix_y)


[[74 37 30]
 [78 64 36]
 [70 23 86]]

[[28  7 51]
 [93 36 93]
 [58 92 50]]


In [55]:
resulting_matrix = matrix_x * matrix_y #elements wise multiplication
print(resulting_matrix)

[[2072  259 1530]
 [7254 2304 3348]
 [4060 2116 4300]]


##Using NumPy, create a 1000-element array of random integers between 1 and 1000. Calculate the cumulative sum of the array and print the 10th, 100th, and 500th elements of the cumulative sum array.

In [58]:
thousand_array = np.random.randint(0,1001,1000)
cummulative_sum = np.cumsum(thousand_array)
print("10 th element is : ", cummulative_sum[9])
print("100 th element is : ", cummulative_sum[99])
print("500 th element is : ", cummulative_sum[499])

10 th element is :  5197
100 th element is :  51803
500 th element is :  242293


##Write a Python program using NumPy to create a 10x10 matrix filled with random integers between 1 and 100. Find the minimum and maximum values of the matrix along with their indices.

In [60]:
matrix_a = np.random.randint(0,101,(10,10))
print(matrix_a)
print("max element is : ",np.max(matrix_a))
print("min element is : ",np.min(matrix_a))

[[ 39 100  25  38  47  28  15  22  10  71]
 [ 62  60  85  50  93  23   2  82   7   7]
 [ 86  64  40  76  84  68  39  11  31  31]
 [ 21  87  93  80  72  54  99  91  28  26]
 [  1  95  64  75  51  21  67  45  47  60]
 [ 57   3   5  82  89  90  83  57  46  24]
 [ 24   8  71   6  39  49  64  41  81  34]
 [ 18  77  26   2  41  78  24  96  28  22]
 [ 90  85  38  12  56  67  81  19  82  79]
 [ 25  65  51   4  59  34   1 100  38   4]]
max element is :  100
min element is :  1


##Write a Python program using NumPy to create a 5x5 matrix filled with random floats between 0 and 1. Replace the maximum value in the matrix with 0 and print the original and modified matrices.

In [82]:
array_b = np.random.uniform(0,1,(5,5))
array_b

array([[0.13211345, 0.90678461, 0.07506147, 0.39929456, 0.98506213],
       [0.05472209, 0.00349308, 0.94446759, 0.19179832, 0.37385227],
       [0.09755038, 0.18195921, 0.85679635, 0.7257676 , 0.80545079],
       [0.75936388, 0.44384145, 0.69538186, 0.33535764, 0.73524938],
       [0.77630027, 0.21212009, 0.87831094, 0.44015609, 0.5527566 ]])

In [79]:
min_index_flat = np.argmin(array_b)
print(min_index_flat)

15


In [80]:
min_row,min_column = np.unravel_index(min_index_flat,array_b.shape)
print(min_row,min_column)

3 0


In [84]:
print("before matrix",array_b)
print()
array_b[min_row,min_column] = 0
print("after matrix",array_b)


before matrix [[0.13211345 0.90678461 0.07506147 0.39929456 0.98506213]
 [0.05472209 0.00349308 0.94446759 0.19179832 0.37385227]
 [0.09755038 0.18195921 0.85679635 0.7257676  0.80545079]
 [0.         0.44384145 0.69538186 0.33535764 0.73524938]
 [0.77630027 0.21212009 0.87831094 0.44015609 0.5527566 ]]

after matrix [[0.13211345 0.90678461 0.07506147 0.39929456 0.98506213]
 [0.05472209 0.00349308 0.94446759 0.19179832 0.37385227]
 [0.09755038 0.18195921 0.85679635 0.7257676  0.80545079]
 [0.         0.44384145 0.69538186 0.33535764 0.73524938]
 [0.77630027 0.21212009 0.87831094 0.44015609 0.5527566 ]]


In [85]:
import numpy as np

array_b = np.random.uniform(0, 1, (5, 5))
min_index_flat = np.argmin(array_b)
min_row, min_col = np.unravel_index(min_index_flat, array_b.shape)

print("Before matrix:\n", array_b)
print(f"\nMinimum value: {array_b[min_row, min_col]} at position ({min_row}, {min_col})")

array_b[min_row, min_col] = 0

print("\nAfter matrix:\n", array_b)

Before matrix:
 [[0.66541098 0.92561999 0.55196963 0.44705843 0.46651653]
 [0.43367695 0.52603441 0.1452003  0.09120279 0.48598188]
 [0.36445064 0.55759661 0.67949975 0.88217121 0.48306644]
 [0.17904631 0.67188088 0.85307837 0.04246135 0.14964051]
 [0.20036451 0.36980859 0.77419876 0.65000271 0.11068144]]

Minimum value: 0.04246135216725189 at position (3, 3)

After matrix:
 [[0.66541098 0.92561999 0.55196963 0.44705843 0.46651653]
 [0.43367695 0.52603441 0.1452003  0.09120279 0.48598188]
 [0.36445064 0.55759661 0.67949975 0.88217121 0.48306644]
 [0.17904631 0.67188088 0.85307837 0.         0.14964051]
 [0.20036451 0.36980859 0.77419876 0.65000271 0.11068144]]


##Write a Python program using NumPy to create a 1D array of 20 elements with random integers between 1 and 100. Calculate the number of even and odd elements in the array and print the result.


In [86]:
arr_c = np.random.randint(1,101,20)
arr_c

array([ 42,  79,  43,  20,  16,  98,  60,  70,  25,  90,  48,  70,  80,
        10,  27,  31,  66,  14, 100,  91])

In [90]:

result_even_odd = np.where(arr_c % 2 ==0,"true","fasle")
even_count = np.sum(arr_c % 2 ==0)
odd_count = np.sum(arr_c % 2 !=0)

print("even_count",even_count)
print("odd_count",odd_count)

even_count 14
odd_count 6


##Write a Python program using NumPy to create a 2D array of size 8x8, where the outer border elements are set to 1 and the inner elements are set to 0. Print the resulting array.

In [91]:
arr = np.zeros((8, 8), dtype=int)

# Set the outer border elements to 1
arr[0, :] = 1       # Top row
arr[-1, :] = 1      # Bottom row
arr[:, 0] = 1       # Left column
arr[:, -1] = 1      # Right column


print(arr)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
