In [1]:
!pip install numpy

In [3]:
import numpy as np

#how to create first array
array1 = np.array([1,2,3,4,5]) #pass it as list of elements

print(array1)

[1 2 3 4 5]


In [5]:
#properties associated with numpy arrays

print("Array 1 NDim", array1.ndim)
print("Array 1 Shape", array1.shape)
print("Array 1 Size", array1.size)
print("Array 1 datatype", array1.dtype)

Array 1 NDim 1
Array 1 Shape (5,)
Array 1 Size 5
Array 1 datatype int64


In [13]:
array2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("Array 2 : ")
print(array2)

print("Array 2 NDim", array2.ndim)
print("Array 2 Shape", array2.shape)
print("Array 2 Size", array2.size)
print("Array 2 datatype", array2.dtype)

Array 2 : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Array 2 NDim 2
Array 2 Shape (2, 5)
Array 2 Size 10
Array 2 datatype int64


In [14]:
# Reshaping the array

array3 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("Array3")
print(array3)

print("-------")

print("After Reshaping")

print(array3.reshape(5,3))

Array3
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-------
After Reshaping
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [15]:
print(array3.reshape(15,1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


In [16]:
#indexing and slicing in arrays

# numpy indexing and slicing is the same as python lists

data  = np.array([1,2,3])



In [17]:
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

1
2
[1 2]
[2 3]
[2 3]


In [18]:
np.zeros(10,dtype = np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [22]:
np.linspace(0,10, num = 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
# Adding and sorting elements in a numpy array

array4 = np.array([3,5,1,2,6,4,9,7])


In [25]:
np.sort(array4)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [26]:
array4

array([3, 5, 1, 2, 6, 4, 9, 7])

In [28]:
#arrays can be concatinated

x = np.array([[1,2],[4,5]])

print(x)
print("-----")

y = np.array([[6,7]])

print(y)
print("-----")

print(np.concatenate((x,y),axis =0))


[[1 2]
 [4 5]]
-----
[[6 7]]
-----
[[1 2]
 [4 5]
 [6 7]]


In [31]:
print(np.concatenate((x,y.T),axis = 1))

[[1 2 6]
 [4 5 7]]


In [33]:
#basic array operations

array5 = np.array([1,2])

array6 = np.ones(2, dtype =int)

print(array5)
print(array6)

[1 2]
[1 1]


In [34]:
array5+array6

array([2, 3])

In [35]:
array5-array6

array([0, 1])

In [36]:
array5*array6

array([1, 2])

In [38]:
## summation of values in a array

array7 = np.arange(2,20,2)
print(array7)

[ 2  4  6  8 10 12 14 16 18]


In [39]:
array7.sum()

np.int64(90)

In [40]:
array7.min()

np.int64(2)

In [42]:
array7.max()

np.int64(18)

In [43]:
array7.mean()

np.float64(10.0)

In [45]:
#Broadcasting

array8 = np.array([1,3,5,7])

array8 * 3.14

array([ 3.14,  9.42, 15.7 , 21.98])

In [49]:
# filtering in Numpy arrays

array9 = np.array([10,12,8,4,5,1,7,22,40,6])

In [51]:
array9 > 20

array([False, False, False, False, False, False, False,  True,  True,
       False])

In [53]:
array9[array9 > 20]

array([22, 40])

In [56]:
array9[array9 <= 10]

array([10,  8,  4,  5,  1,  7,  6])

In [62]:
(array9>=10) & (array9 <=30)

array([ True,  True, False, False, False, False, False,  True, False,
       False])

In [64]:
array9[(array9>=10) & (array9 <=30)]

array([10, 12, 22])

In [65]:
# how to save and load Numpy objects
array10 = np.array([1,2,3,4,5,6,7,8,9])
array10


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.save("tentharray",array10)

In [67]:
array11  = np.load('tentharray.npy')

In [69]:
print(array11)

[1 2 3 4 5 6 7 8 9]


In [71]:
np.savetxt('tenth_array_csv.csv',array10)

In [73]:
!ls

sample_data  tenth_array_csv.csv  tentharray.npy


In [74]:
! cat tenth_array_csv.csv

1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
4.000000000000000000e+00
5.000000000000000000e+00
6.000000000000000000e+00
7.000000000000000000e+00
8.000000000000000000e+00
9.000000000000000000e+00


In [75]:
array12 = np.loadtxt('tenth_array_csv.csv')

In [78]:
print(array12)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
